email: your-email@example.com
color_scheme: color
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#"/criando-documentacoes-github-pages-markdown-jekyll-2022-01-18"
baseurl: "/documantation"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
#logo: "/assets/img/logo.svg"
# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

mermaid:
  # Versão da biblioteca Mermaid.js
  # Escolha uma versão disponível em https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"

  # Configuração opcional do tema Mermaid (por padrão: 'default')
  #theme: "default" # Pode ser "dark", "neutral", "forest", etc.
